<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TestSuit1</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <lastRun>2018-09-19T16:27:46</lastRun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>11dcfce0-069f-4669-b799-cc823db4256f</testSuiteGuid>
   <testCaseLink>
      <guid>6c5af515-69ab-42e7-b784-618d980904c3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TestCase4</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>deed5b0e-627d-4beb-ac54-382b7a4ab7dd</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/demo_account</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>deed5b0e-627d-4beb-ac54-382b7a4ab7dd</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>demo_usn</value>
         <variableId>0d5b108d-1bfd-4d15-8a11-f3c70e1faa9c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>deed5b0e-627d-4beb-ac54-382b7a4ab7dd</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>demo_pwd</value>
         <variableId>b267568f-2a28-45d3-ae80-5a0eea970917</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
